### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Tom Cruise",
  "email": "tom@example.com",
  "password": "password",
  "password_confirmation": "password"
}